# Generated by Django 4.2.1 on 2025-02-13 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcoop_app', '0015_alter_loan_control_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentschedule',
            name='original_principal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
